apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grade-submission-api
  template:
    metadata:
      labels:
        app: grade-submission-api
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: grade-submission-api
        image: ghcr.io/zxcamon4ik/kubernetes-cicd:839d035437e359543622bf3f95732f911c47e348
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: grade-submission-api
  namespace: default
spec:
  selector:
    app: grade-submission-api
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP